name: CI/CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
            
      - name: Docker build & push
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            mateuspada/kube-news:v${{ github.run_number }}
            mateuspada/kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Configuração do Kubectl
        shell: bash
        run: |
          aws eks update-kubeconfig --name eks-imersao --region us-east-1

      - name: Deploy PostgreSQL
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s/deploy-kubedev-postgresql.yaml
          images: |
            postgres:15
            
      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.1
        with:
          time: 30s
            
      - name: Deploy KubeDev App
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s/deploy-kubedev.yaml
          images: |
            mateuspada/kube-news:v${{ github.run_number }}